import '../database/archivio_locale.dart';

const String cartellaImmaginiEsercizi = 'assets/esercizi';
const String immagineEsercizioPlaceholder =
    'assets/esercizi/placeholder.png';

const Map<String, String> mappaImmaginiEsercizi = {
  'Affondi manubri': 'assets/esercizi/affondi-manubri.png',
  'Alzate laterali manubri': 'assets/esercizi/alzate-laterali-manubri.png',
  'Alzate laterali manubri busto 90': 'assets/esercizi/alzate-laterali-manubri-busto-90.png',
  'Alzate laterali manubri seduto': 'assets/esercizi/alzate-laterali-manubri-seduto.png',
  'Alzate laterali seduto busto 90': 'assets/esercizi/alzate-laterali-seduto-busto-90.png',
  'Alzate laterali singolo cavo': 'assets/esercizi/alzate-laterali-singolo-cavo.png',
  'Aperture inverse': 'assets/esercizi/aperture-inverse.png',
  'Aperture panca piana manubri': 'assets/esercizi/aperture-panca-piana-manubri.png',
  'Arnold press': 'assets/esercizi/arnold-press.png',
  'Lat machine inverso': 'assets/esercizi/at-machine-inverso.png',
  'Burpees': 'assets/esercizi/burpees.png',
  'Calf machine seduto': 'assets/esercizi/calf-machine-seduto.png',
  'Calf machine': 'assets/esercizi/calf-machine.png',
  'Calf pressa orizzontale': 'assets/esercizi/calf-pressa-orizzontale.png',
  'Chest press': 'assets/esercizi/chest-press.png',
  'Chiusure cavi alti': 'assets/esercizi/chiusure-cavi-alti.png',
  'Chiusure cavi bassi': 'assets/esercizi/chiusure-cavi-bassi.png',
  'Crossover cavi alti': 'assets/esercizi/crossover-cavi-alti.png',
  'Crunch con wallball': 'assets/esercizi/crunch-con-wallball.png',
  'Crunch inverso': 'assets/esercizi/crunch-inverso.png',
  'Crunch panca reclinata': 'assets/esercizi/crunch-panca-reclinata.png',
  'Crunch terra': 'assets/esercizi/crunch-terra.png',
  'Crunch terra alternato': 'assets/esercizi/crunch-terra-alternato.png',
  'Curl bilanciere': 'assets/esercizi/curl-bilanciere.png',
  'Curl cavi alti': 'assets/esercizi/curl-cavi-alti.png',
  'Curl manubri martello alternato': 'assets/esercizi/curl-manubri-martello-alternato.png',
  'Curl manubri seduto': 'assets/esercizi/curl-manubri-seduto.png',
  'Curl panca scott bilanciere': 'assets/esercizi/curl-panca-scott-bilanciere.png',
  'Dips parallele': 'assets/esercizi/dips-parallele.png',
  'French press 1 manubrio seduto': 'assets/esercizi/french-pres-1man-seduto.png',
  'French press 2 manubri panca': 'assets/esercizi/french-press-2man-panca.png',
  'Panca piana': 'assets/esercizi/panca_piana.png',
  'Trazioni alla sbarra': 'assets/esercizi/trazioni_sbarra.png',
  'Squat': 'assets/esercizi/squat.png',
  'Curl manubri': 'assets/esercizi/curl_manubri.png',
  'French press bilanciere': 'assets/esercizi/french-press-bilanciere.png',
  'Hack squat': 'assets/esercizi/hack-squat.png',
  'Lat machine avanti': 'assets/esercizi/lat-machine-avanti.png',
  'Leg curl': 'assets/esercizi/leg-curl.png',
  'Leg curl seduto': 'assets/esercizi/leg-curl-seduto.png',
  'Leg extension': 'assets/esercizi/leg-extension.png',
  'Leg press': 'assets/esercizi/leg-press.png',
  'Leg raise': 'assets/esercizi/leg-raise.png',
  'Plank': 'assets/esercizi/plank.png',
  'Push cavi': 'assets/esercizi/push-cavi.png',
  'Push up': 'assets/esercizi/push-up.png',
  'Spinte manubri panca piana': 'assets/esercizi/spinte-manubri-panca-piana.png',
  'Spinte panca alta manubri': 'assets/esercizi/spinte-panca-alta-manubri.png',
  'Spinte seduto manubri': 'assets/esercizi/spinte-seduto-manubri.png',
  'Squat bilanciere': 'assets/esercizi/squat-bilanciere.png',
  'Squat multipower': 'assets/esercizi/squat-multipower.png',
  'Stacchi gambe tese': 'assets/esercizi/stacchi-gambe-tese.png',
  'Upper back': 'assets/esercizi/upper-back.png',
  'Vertical row': 'assets/esercizi/vertical-row.png',
  'Pullover manubrio': 'assets/esercizi/PULLOVER-MANUBRIO.png',
  'Accosciata cavo basso': 'assets/esercizi/ACCOSCIATA-CAVO-BASSO.png',
  'Aperture manubri panca alta': 'assets/esercizi/APERTURE-MANUBRI-PANCA-ALTA.png',
  'Bayesian curl singolo cavo basso': 'assets/esercizi/BAYESIAN-CURL-SINGOLO-CAVO-BASSO.png',
  'Bike seduto': 'assets/esercizi/BIKE-SEDUTO.png',
  'Corsa tappeto': 'assets/esercizi/CORSA-TAPPETO.png',
  'Cyclette': 'assets/esercizi/CYCLETTE.png',
  'Distensioni bilanciere panca piana multipower': 'assets/esercizi/distensioni-bilanciere-panca-piana-multipower.png',
  'Hyperextension': 'assets/esercizi/HYPEXTENSION.png',
  'Pressa 45': 'assets/esercizi/PRESSA-45.png',
  'Pulley triangolo': 'assets/esercizi/PULLEY-TRIANGOLO.png',
  'Rematore bilanciere': 'assets/esercizi/REMATORE-BILANCIERE.png',
  'Rematore manubrio su panca': 'assets/esercizi/REMATORE-MANUBRIO-SU-PANCA.png',
  'Rematore 1 manubrio busto 90': 'assets/esercizi/1MAN-BUSTO90.png',
  'Spinte bilanciere panca presa stretta': 'assets/esercizi/SPINTE-BILANCIERE-PANCA-PRESA-STRETTA.png',
  'Trazioni pulley basso': 'assets/esercizi/TRAZIONI-PULLEY-BASSO.png',
  'Trazioni Tbar bilanciere': 'assets/esercizi/Trazioni-Tbar_Bilanciere.png',
};

const Map<String, String> mappaVideoEsercizi = {
  'Affondi manubri': 'assets/esercizi/affondi-manubri-video.mp4',
  'Alzate laterali manubri': 'assets/esercizi/alzate-laterali-manubri-video.mp4',
  'Alzate laterali manubri busto 90': 'assets/esercizi/alzate-laterali-manubri-busto-90-video.mp4',
  'Alzate laterali manubri seduto': 'assets/esercizi/alzate-laterali-manubri-seduto-video.mp4',
  'Alzate laterali seduto busto 90': 'assets/esercizi/alzate-laterali-seduto-busto-90-video.mp4',
  'Alzate laterali singolo cavo': 'assets/esercizi/alzate-laterali-singolo-cavo-video.mp4',
  'Aperture inverse': 'assets/esercizi/aperture-inverse-video.mp4',
  'Aperture panca piana manubri': 'assets/esercizi/aperture-panca-piana-manubri-video.mp4',
  'Arnold press': 'assets/esercizi/arnold-press-video.mp4',
  'Burpees': 'assets/esercizi/burpees-video.mp4',
  'Calf machine seduto': 'assets/esercizi/calf-machine-seduto-video.mp4',
  'Calf machine': 'assets/esercizi/calf-machine-video.mp4',
  'Calf pressa orizzontale': 'assets/esercizi/calf-pressa-orizzontale-video.mp4',
  'Chest press': 'assets/esercizi/chest-press-video.mp4',
  'Chiusure cavi alti': 'assets/esercizi/chiusure-cavi-alti.mp4',
  'Chiusure cavi bassi': 'assets/esercizi/chiusure-cavi-bassi-video.mp4',
  'Crossover cavi alti': 'assets/esercizi/crossover-cavi-alti-video.mp4',
  'Crunch con wallball': 'assets/esercizi/crunch-con-wallball-video.mp4',
  'Crunch inverso': 'assets/esercizi/crunch-inverso-video.mp4',
  'Crunch panca reclinata': 'assets/esercizi/crunch-panca-reclinata-video.mp4',
  'Crunch terra': 'assets/esercizi/crunch-terra-video.mp4',
  'Crunch terra alternato': 'assets/esercizi/crunch-terra-alternato-video.mp4',
  'Curl bicipiti': 'assets/esercizi/curl-bicipiti-video.mp4',
  'Curl bilanciere': 'assets/esercizi/curl-bilanciere-video.mp4',
  'Curl cavi alti': 'assets/esercizi/curl-cavi-alti-video.mp4',
  'Curl manubri martello alternato': 'assets/esercizi/curl-manubri-martello-alternato-video.mp4',
  'Curl manubri seduto': 'assets/esercizi/curl-manubri-seduto-video.mp4',
  'Curl panca scott bilanciere': 'assets/esercizi/curl-panca-scott-bilanciere-video.mp4',
  'Dips parallele': 'assets/esercizi/dips-parallele-video.mp4',
  'French press 1 manubrio seduto': 'assets/esercizi/french-pres-1man-seduto-video.mp4',
  'French press 2 manubri panca': 'assets/esercizi/french-press-2man-panca-video.mp4',
  'Hack squat': 'assets/esercizi/hack-squat-video.mp4',
  'Lat machine avanti': 'assets/esercizi/lat-machine-avanti-video.mp4',
  'Leg curl': 'assets/esercizi/leg-curl-video.mp4',
  'Leg curl seduto': 'assets/esercizi/leg-curl-seduto-video.mp4',
  'Leg extension': 'assets/esercizi/leg-extension-video.mp4',
  'Leg press': 'assets/esercizi/leg-press-video.mp4',
  'Leg raise': 'assets/esercizi/leg-raise-video.mp4',
  'Panca piana': 'assets/esercizi/panca_piana-video.mp4',
  'Push up': 'assets/esercizi/push-up-video.mp4',
  'Spinte manubri panca piana': 'assets/esercizi/spinte-manubri-panca-piana-video.mp4',
  'Spinte panca alta manubri': 'assets/esercizi/spinte-panca-alta-manubri.mp4',
  'Spinte seduto manubri': 'assets/esercizi/spinte-seduto-manubri-video.mp4',
  'Squat bilanciere': 'assets/esercizi/squat-bilanciere-video.mp4',
  'Squat multipower': 'assets/esercizi/squat-multipower-video.mp4',
  'Stacchi gambe tese': 'assets/esercizi/stacchi-gambe-tese-video.mp4',
  'Upper back': 'assets/esercizi/upper-back-video.mp4',
  'Vertical row': 'assets/esercizi/vertical-row-video.mp4',
  'Accosciata cavo basso': 'assets/esercizi/ACCOSCIATA-CAVO-BASSO-VIDEO.mp4',
  'Aperture manubri panca alta': 'assets/esercizi/APERTURE-MANUBRI-PANCA-ALTA-VIDEO.mp4',
  'Bayesian curl singolo cavo basso': 'assets/esercizi/BAYESIAN-CURL-SINGOLO-CAVO-BASSO-VIDEO.mp4',
  'Distensioni bilanciere panca piana multipower': 'assets/esercizi/distensioni-bilanciere-panca-piana-multipower-video.mp4',
  'Hyperextension': 'assets/esercizi/HYPEXTENSION-VIDEO.mp4',
  'Pressa 45': 'assets/esercizi/PRESSA-45-VIDEO.mp4',
  'Pulley triangolo': 'assets/esercizi/PULLEY-TRIANGOLO-VIDEO.mp4',
  'Pullover manubrio': 'assets/esercizi/PULLOVER-MANUBRIO-VIDEO.mp4',
  'Rematore bilanciere': 'assets/esercizi/REMATORE-BILANCIERE-VIDEO.mp4',
  'Rematore manubrio su panca': 'assets/esercizi/REMATORE-MANUBRIO-SU-PANCA-VIDEO.mp4',
  'Rematore 1 manubrio busto 90': 'assets/esercizi/1MAN-BUSTO90-VIDEO.mp4',
  'Spinte bilanciere panca presa stretta': 'assets/esercizi/SPINTE-BILANCIERE-PANCA-PRESA-STRETTA-VIDEO.mp4',
  'Trazioni pulley basso': 'assets/esercizi/TRAZIONI-PULLEY-BASSO-VIDEO.mp4',
  'Trazioni Tbar bilanciere': 'assets/esercizi/Trazioni-Tbar_Bilanciere-video.mp4',
};

String percorsoImmagineEsercizio(EserciziData esercizio) {
  final percorsoLocale = esercizio.urlImmagine;
  if (percorsoLocale != null && percorsoLocale.isNotEmpty) {
    return percorsoLocale;
  }
  return mappaImmaginiEsercizi[esercizio.nome] ??
      immagineEsercizioPlaceholder;
}

String? percorsoVideoEsercizio(EserciziData esercizio) {
  final percorso = mappaVideoEsercizi[esercizio.nome];
  if (percorso == null || percorso.trim().isEmpty) return null;
  return percorso;
}

bool immagineEAsset(String percorso) => percorso.startsWith('assets/');
